name: Build x86 and ARM64 images

on: workflow_dispatch

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
        id: go

      - name: Clean up docker
        run: docker system prune -a --volumes -f

      - name: Clean up stale docker images
        run: docker image prune -f

      - name: Build
        run: make multi-arch-cni-build-push

  # Disable arm-build
  # build_arm:
  #   name: Build ARM64
  #   runs-on: [self-hosted, linux, arm64]
  #   steps:

  #   - name: Set up Go 1.18
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: '1.18'
  #     id: go

  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2

  #   - name: Clean up docker
  #     run:  docker system prune -a --volumes -f

  #   - name: Clean up stale docker images
  #     run: sudo docker image prune -f

  #   - name: Build
  #     run: make docker all
