name: VPC CNI Release

on: [push, workflow_dispatch]

env:
  GITHUB_USERNAME: ${{ secrets.EKS_BOT_GITHUB_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.EKS_BOT_GITHUB_TOKEN }}

jobs:
  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Attach release artifacts
        run: make release
      - name: Create eks-charts PR
        run: make ekscharts-sync-release
      - name: Create sample manifests PR
        run: make config-folder-sync
